# apiVersion: v1
# kind: Service
# metadata:
#   name: huatah-service
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 3000
#       targetPort: 3000
#   selector:
#     app: huatah
---
apiVersion: v1
kind: Service
metadata:
  name: huatah-service-np
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: huatah
