apiVersion: apps/v1
kind: Deployment
metadata:
  name: huatah-backend-deployment
  labels:
    app: huatah-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: huatah-backend
  template:
    metadata:
      labels:
        app: huatah-backend
    spec:
      containers:
        - name: huatah
          image: ricoharsono/huatah-backend:latest
          ports:
            - containerPort: 3030
          imagePullPolicy: Always
          volumeMounts:
            - name: valo-config
              mountPath: /app/data/Valorant.json
              subPath: Valorant.json
      volumes:
        - name : valo-config
          configMap:
            name: valo-config

