apiVersion: v1
kind: Service
metadata:
  name: backend-service-np
spec:
  type: NodePort
  ports:
    - port: 3030
      targetPort: 3030
      protocol: TCP
      nodePort: 30000
  selector:
    app: huatah-backend
