apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: huatah-co-tls
  namespace: default
spec:
  secretName: huatah-co-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: huatah.co
  dnsNames:
    - huatah.co
    - www.huatah.co
