apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com
  namespace: default
spec:
  secretName: example-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: huatah.co
  dnsNames:
    - huatah.co
    - www.huatah.co
