apiVersion: v1
kind: Pod
metadata:
  name: mysql-backup
spec:
  containers:
    - name: backup
      image: busybox
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      volumeMounts:
        - name: backup-storage
          mountPath: /backup
  volumes:
    - name: backup-storage
      persistentVolumeClaim:
        claimName: mysql-backup-pvc
