apiVersion: v1
kind: Pod
metadata:
  name: mysql-temp
spec:
  containers:
    - name: mysql
      image: mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: test123
      volumeMounts:
        - name: temp-data
          mountPath: /var/lib/mysql
  volumes:
    - name: temp-data
      emptyDir: {}
